### ISSUE TITLE
Expected to see 'margin' with a different value inside 'body {}' 

### ISSUE THREAD

**Issue by scallsen** [scallsen/stacked-nav#1]
Hi @thomasjbradley ,
I've completed my stacked navigation site and have it looking just like the example, and am left with a single Markbot detected error. **The margin value is incorrect.**
<img width="820" alt="screen shot 2016-02-11 at 5 41 34 pm" src="https://cloud.githubusercontent.com/assets/16653087/12993504/89113f08-d0e8-11e5-9df4-acece07de624.png">

In the screenshot provided with the assignment there appears to be no margin around the header (which would be enclosed in the body). 
![index](https://cloud.githubusercontent.com/assets/16653087/12993434/11dc9220-d0e8-11e5-9955-47e007db8559.jpg)

Markbot does not accept zero either. If there is something I am missing, please let me know.

–Simon

**Comment by thomasjbradley** [comment]
I'd like to see your code but it hasn't been committed and synced to GitHub.

What did you write for `margin` on the `body`?

**Comment by scallsen** [comment]
Oh it looks like I haven't synced it, sorry about that; I've just synced it now.
I have set it to `inherit`, `auto`, `zero`, or `1 rem` (as the screenshot appears to have no margin) and they all failed to pass. 

[Here's a link to a pastebin of my main.css in case it's still not visible.
](http://pastebin.com/5JdYwcvL)
`code`

**Comment by thomasjbradley** [comment]
What about `0`, the number?

**Comment by scallsen** [comment]
Well, it looks like that worked. 
Won't be making that mistake twice...
